app/experts/__init__.py
from flask import Blueprint

experts = Blueprint('experts', __name__)

from . import views

app/experts/views.py
from flask import render_template
from . import experts
from flask.ext.paginate import Pagination
from flask import request
from ..models import Experts
import hashlib
import json
from ..functions.network import create_simmple_graph

Expert =Experts()

@experts.route('/experts')
def get_experts():
    search = False
    q = request.args.get('q')
    if q:
        search = True
        search_parameter = request.args.get('q', 1)
    try:
        page = int(request.args.get('page', 1))
    except ValueError:
        page = 1
    if(search):
        list = Expert.get_expert_by_search(search_parameter)
        return render_template('expertList.html',list=list)

    else:
        list = Expert.get_paged(page)
        count = Expert.get_count()
        pagination = Pagination(page=page, total=count[0].count, search=search, record_name='experts', per_page=20)
        return render_template('expertList.html',list=list, pagination=pagination)



@experts.route('/experts/<username>')
def user(username):
    user = Expert.get_expert_by_name(username)
    gravatar= hashlib.md5("{0}@example.com".format(user[0].name)).hexdigest()
    dbjson= create_simmple_graph(username)
    gravatar_url= 'http://www.gravatar.com/avatar/'+gravatar+'?s=200'
    categories={'Contribution':['Semantic','Sentiment'],'Relationship':['Type','Strength'],'Metadata':['Structural-Depth','Structural-Coverage','Descriptive'],'Administrative':['Background','Reputation']}
    return render_template('experts.html', user=user[0],grav = gravatar_url,categories=categories,da=dbjson)

@experts.route('/expertssave', methods=['POST'])

def save_proprieties():
    option =  request.form['selected']
    use = request.form['user'];
    feature = request.form['feature']
    Expert.update_expert_by_property(use.strip(),feature,option)
    return json.dumps({'status':'OK'});

app/granules/__init__.py
from flask import Blueprint

granules = Blueprint('granules', __name__)

from . import views

app/granules/views.py
from flask import render_template
from . import granules
from flask.ext.paginate import Pagination
from flask import request
from ..models import Granules
import random
from collections import OrderedDict
import hashlib

Granules =Granules()

@granules.route('/granules')
def get_granules():
    search = False
    q = request.args.get('q')
    if q:
        search = True
        search_parameter = request.args.get('q', 1)
    try:
        page = int(request.args.get('page', 1))
    except ValueError:
        page = 1
    if(search):
        list = Granules.get_granules_by_search(search_parameter)
        return render_template('granules.html',list=list)

    else:

        list = Granules.get_paged(page)
        count = Granules.get_count()

        for i,k in enumerate(list):
            try:
                grans =[]
                list[i].count = random.randint(100,500)
                #for i in range (1,random.randint(2,4)):
                grans.append('G'+str(random.randint(1,22)))
                list[i].gran = 'G'+str(random.randint(1,22))
            except IndexError:
                continue
        pagination = Pagination(page=page, total=count[0].count, search=search, record_name='granules', per_page=20)
        return render_template('granules.html',list=list, pagination=pagination)



@granules.route('/granules/<name>')
def granule(name):
    granule = Granules.get_granules_by_name(name)
    gravatar_url= ''
    return render_template('granule.html', user=granule[0],grav = gravatar_url)

app/graph/__init__.py
from flask import Blueprint

graph = Blueprint('graph', __name__)

from . import views

app/graph/views.py
from flask import render_template
from . import graph

@graph.route('/graph', methods=['GET', 'POST'])
def graph():
    return render_template('graph.html')

app/orientdb/__init__.py
from flask import Blueprint

orient = Blueprint('orient', __name__)

from . import views

app/orientdb/views.py
from flask import render_template
from . import orient


@orient.route('/orientdb')
def graph():
    return render_template('orientdb.html')

app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__)

from . import views

app/posts/views.py
from flask import render_template,flash
from . import posts
from flask.ext.paginate import Pagination
from flask import request
from ..models import Experts,Posts
from .. import cache
Post = Posts()
Expert =Experts()
import hashlib


@posts.route('/posts')
def get_posts():
    search = False
    q = request.args.get('q')
    if q:
        search = True
        search_parameter = request.args.get('q', 1)
    try:
        page = int(request.args.get('page', 1))
    except ValueError:
        page = 1
    if(search):
        list = Post.get_paged(search_parameter)
        return render_template('posts.html',list=list)

    else:
        count = cache.get('postcount')
        #list = cache.get('posts'+str(page))
        if count is None:
            count = Post.get_count()
            count = count[0].count
            cache.set('postcount', count, timeout=300)
        list = Post.get_paged(page)
        #if list is None:
        #
        #    cache.set('posts'+str(page),set(list),timeout=300)
        pagination = Pagination(page=page, total=count, search=search, record_name='experts', per_page=10)

        return render_template('posts.html',list=list, pagination=pagination)

@posts.route('/post/<postid>')
def get_post(postid):
    post = Post.get_post_id(postid)
    answers = None
    if Post.check_if_question(postid):
        answers= Post.get_answer_by_id(postid)

    return render_template('post.html', post=post[0],answers=answers)

app/templates/base.html
{% extends "material/base.html" %}
{% import "material/utils.html" as util %}
{% import "material/wtf.html" as wtf %}

{% block title %}Hier kommt der ladida{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

{% endblock %}

{% block navbar %}
<nav>
    <div class="nav-wrapper ">
      <a href="#" class="brand-logo right"><img style="height: 65px" src=" {{ url_for('static', filename='images/logo.png') }}"></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><a href="{{ url_for('surface.index') }}">KCFS</a></li>
          <li><a href="{{ url_for('granules.get_granules') }}">Concepts</a></li>
          <li><a href="{{ url_for('experts.get_experts') }}">Knowlegde Carriers</a></li>
          <li><a href="{{ url_for('posts.get_posts') }}">Contributions</a></li>
          <li><a href="{{ url_for('graph.graph') }}">Graph</a></li>
      </ul>
    </div>
  </nav>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}

     <script> jQuery(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    jQuery('.modal-trigger').leanModal();

  });

          </script>
    <script  src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

app/templates/expertList.html
{% extends 'base.html' %}
{% block title %}Knowledge Carrier{% endblock %}

{% block page_content %}
<div id="demo">
  <h1>List of Knowledge Carriers</h1>
    <div class="sw">
    <form action="{{ url_for('experts.get_experts',q=q) }}" method="get">
      <input type="search" name="q" class="search" placeholder="Search for an expert" />
      <button class="go"><span class="entypo-search"></span></button>
    </form>
  </div>

  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
            <th>Age</th>
            <th>Location</th>
          <th>Reputation</th>

        </tr>
      </thead>
      <tbody>
      {% for i in list %}
        <tr>
          <td data-title="ID">{{i.ID}}</td>
          <td data-title="Name"><a href="{{ url_for('experts.user', username=i.name) }}" >{{i.name}}</a></td>
            <td data-title="Age">{{i.Age}}</td>
            <td data-title="Location">{{i.Location}}</td>
          <td data-title="Reputation">{{i.Reputation}}</td>
        </tr>
      {% endfor %}

      </tbody>
    </table>
  {% if list[0] is not defined %}
      <h4>No results found</h4>
  {% endif %}


  </div>
</div>
{% if pagination %}
    {{ pagination.links }}
{% else %}
    <a href="{{ url_for('experts.get_experts') }}">Back to the overview</a>
{% endif %}

{% endblock %}

app/templates/experts.html
{% extends 'base.html' %}
{% block title %}Profil - {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <div class="profile-img">
    </div>
    <div class="profile-header card-panel row " style="margin:0px 0px;">
<div class="col s1">
        <img class="circle responsive-img " src="{{ grav }}">
</div>
    <!--{% set ran=(1,2,3,4,5,6,7,8,9,10) %}
    {%   set backurl= ran|random %} -->


        {% if user.name or user.location %}
            {% if user.name %}<div class="col s2"><span class="blue-grey-text text-darken-3">Name</span></br>
{{ user.name }}</div>{% endif %}
            {% if user.Location %}
               <div class="col s1"><span class="blue-grey-text text-darken-3">Location</span></br><a href="http://maps.google.com/?q={{ user.Location }}">{{ user.Location }}</a></div>
            {% endif %}
        {% endif %}
        <div class="col s2 valign"><span class="blue-grey-text text-darken-3">Member since</span><br> {{ user.CreationDate }}</div>
        <div class="col s2 "><span class="blue-grey-text text-darken-3 ">Last seen</span><br> {{ user.LastAccessDate }}.</div>
        <div class="col s2"><span class="blue-grey-text text-darken-3">Profile views</span></br>{{ user.Views }}</div>
        <div class="col s1"><span class="blue-grey-text text-darken-3">Reputation</span></br>{{ user.Reputation}}</div>
        <div class="col s1"><span class="blue-grey-text text-darken-3">Downvotes</span></br>{{ user.DownVotes }}</div>
   </div>
<div class="card-panel"><h5>Concepts</h5></div>
<div class="graph"></div>

<div class="card-panel"><h5>Settings</h5></div>
<ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>Refinement Values</div>
      <div class="collapsible-body"><div class="collection">
        {% for item in categories.keys() %}
        <div class="row collection-item">
            <div class="col s12 card-title "><h5>{{ item }}</h5></div>

              {% for k in categories[item] %}
                  {% set kaka = (12/categories[item]|length)|int %}
                  {% set sas = k|lower|replace('-','')+'setting' %}

            <div class="col s12 m{{ kaka }} l{{ kaka }}"><span>{{ k }}</span><a data-target="modal{{ sas }}" style="float:right;margin-right: 20px" class="modal-trigger  waves-effect waves-light btn " href="#modal{{ sas }}" id="{{ sas }}first">{% if user[sas] %}{{ user[sas] }}{% else %}Please define{% endif %}</a>
                <div id="modal{{ sas }}" class="modal">
                    <div class="modal-content">
                        <h4>Settings for {{ k }}</h4>
                         <form action="#" method="post" class="{{ sas }}">
                            <p>
                                <input name="group{{ sas }}" type="radio" value="Minor" {% if user[sas] == 'Minor' %}checked="checked" {% endif %}id="{{ sas }}1" />
                                <label for="{{ sas }}1">Minor</label>
                                <input name="group{{ sas }}" type="radio" value="Light" {% if user[sas] == 'Light' %}checked="checked" {% endif %}id="{{ sas }}2" />
                                <label for="{{ sas }}2">Light</label>
                                <input name="group{{ sas }}" type="radio" value="Moderate" {% if user[sas] == 'Moderate' %}checked="checked" {% endif %}id="{{ sas }}3"  />
                                <label for="{{ sas }}3">Moderate</label>
                                <input name="group{{ sas }}" type="radio" value="Strong" {% if user[sas] == 'Strong' %}checked="checked" {% endif %}id="{{ sas }}4"  />
                                <label for="{{ sas }}4">Strong</label>
                                <input name="group{{ sas }}" type="radio" value="Major" {% if user[sas] == 'Major' %}checked="checked" {% endif %}id="{{ sas }}5"  />
                                <label for="{{ sas }}5">Major</label>
                            </p>
                          </form>
                    </div>
                    <div class="modal-footer">
                      <a href="#!" class="modal-action waves-effect waves-blue btn jaja" id="{{ sas }}">Save</a>
                    </div>
                </div>
        </div>
        {% endfor %}
            </div>
        {% endfor %}
        </div>
    </div>
    </li>
  </ul>



</div>
{% endblock %}
    {% block scripts %}
        {{ super() }}
        <script> var username="{{ user.name }} "</script>
        <script  src="{{ url_for('static', filename='expert.js') }}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
        <script>

var width = 960,
    height = 500;

var force = d3.layout.force()
    .size([width, height])
    .charge(-400)
    .linkDistance(40)
    .on("tick", tick);

var drag = force.drag()
    .on("dragstart", dragstart);

var svg = d3.select(".graph").append("svg")
    .attr("width", width)
    .attr("height", height);

var link = svg.selectAll(".link"),
    node = svg.selectAll(".node");
daa = {{ da|safe }}

force.nodes(daa.nodes)
        .links(daa.links)
        .start();

link = link.data(daa.links)
        .enter().append("line")
        .attr("class", "link");

node = node.data(daa.nodes)
        .enter().append("circle")
        .attr("class", "node")
        .attr("r", 12)
        .on("dblclick", dblclick)
        .call(drag);

var labels = svg.selectAll("text")                                      //***NEW
		 			    .data(daa.nodes)
		 			    .enter()
		 			    .append("text")
		 			    .attr({"x":function(d){return d.x -2.5;},
		 					   "y":function(d){return d.y;}})
		 			    .text(function(d){return d.id;})
		 			    .call(force.drag);
force.on("tick", tick); force.start();
function tick() {
  link.attr("x1", function(d) { return d.source.x; })
      .attr("y1", function(d) { return d.source.y; })
      .attr("x2", function(d) { return d.target.x; })
      .attr("y2", function(d) { return d.target.y; });

  node.attr("cx", function(d) { return d.x; })
      .attr("cy", function(d) { return d.y; });
    labels.attr("x", function(d) { return d.x +22.5; })        // **NEW**
                                .attr("y", function(d) { return d.y; });
}

function dblclick(d) {
  d3.select(this).classed("fixed", d.fixed = false);
}

function dragstart(d) {
  d3.select(this).classed("fixed", d.fixed = true);
}

</script>


{% endblock %}

app/templates/granule.html
{% extends 'base.html' %}
{% block title %}Profil - {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <img class="img-rounded profile-thumbnail" src="{{ grav }}">
    <div class="profile-header">
        <h1>{{ user.name }}</h1>
        {% if user.name or user.location %}
        <p>
            {% if user.name %}{{ user.name }}<br>{% endif %}
            {% if user.Location %}
                From <a href="http://maps.google.com/?q={{ user.Location }}">{{ user.Location }}</a><br>
            {% endif %}
        </p>
        {% endif %}

        <p>Member since {{ user.CreationDate }}. Last seen {{ user.LastAccessDate }}.</p>
        <p>{{ user.Views }}  profile views. {{ user.Reputation}} Reputation.</p>
        <p>{{ user.DownVotes }}  Downvotes. {{ user.WebsiteUrl}} WebsiteUrl.</p>


    </div>
</div>
{% endblock %}

app/templates/granules.html
{% extends 'base.html' %}
{% block title %}Profil Liste{% endblock %}

{% block page_content %}
<div id="demo">
  <h1>List of granules</h1>
    <div class="sw">
    <form action="{{ url_for('granules.get_granules',q=q) }}" method="get">
      <input type="search" name="q" class="search" placeholder="Search for a granule" />
      <button class="go"><span class="entypo-search"></span></button>
    </form>
  </div>

  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th>Name</th>
            <th>Level</th>
            <th>In Granules</th>
        </tr>
      </thead>
      <tbody>
      {% for i in list %}
        <tr>
          <td data-title="Name">{{i.name}}</td>
            <td data-title="ID">{{i.Level}}</td>
          <td data-title="ID">{{i.gran}}</td>
        </tr>
      {% endfor %}

      </tbody>
    </table>
  {% if list[0] is not defined %}
      <h4>No results found</h4>
  {% endif %}


  </div>
</div>
{% if pagination %}
    {{ pagination.links }}
{% else %}
    <a href="{{ url_for('experts.get_experts') }}">Back to the overview</a>
{% endif %}

{% endblock %}

app/templates/graph.html
{% extends 'base.html' %}
{% block title %}Graph {% endblock %}

{% block content %}
    <div style="height:100%; overflow: hidden;">

<iframe frameborder='0' noresize='noresize' style='position: relative; background: transparent; width: 100%; height:100%; top:-52px;' src="http://localhost:2480/studio/index.html#/database/test_db/graph" frameborder="0"></iframe>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block page_content %}
    <h2>Query the cube</h2>
  <div class="sw">
    <form action="{{ url_for('surface.index',q=q) }}" method="get">
      <input type="search" name="q" class="search" placeholder="Query the cube..." />
      <button class="go"><span class="entypo-search"></span></button>
    </form>
  </div>
{% endblock %}

app/templates/need.html
{% extends 'base.html' %}
{% block title %}Search for - {{ search_parameter }}{% endblock %}

{% block page_content %}
<div id="demo">
  <h1>Looking for a Knowledge Carrier for {{ search_parameter }}</h1>
    <div class=" btn card-panel hoverable">Concepts</div>
        <div class="card-panel">{{ keywords }}</div><br>
  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
    <div class=" btn card-panel hoverable">Ranking of Knowlegde Carriers</div>
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th>Name</th>
          <th>Contact</th>
          <th>Score</th>
            <th>Details</th>
        </tr>
      </thead>
      <tbody>
      {% for i in list %}
        <tr>
          <td data-title="ID">{{i.name}}</td>
            <td>{{i.name}}@example.com</td>
          <td data-title="Link">
            {{i.score}}
          </td>
          <td data-title="Status"><a href="{{ url_for('surface.index',q=search_parameter,e='TRUE',d=i.score) }}" class="btn button">Details</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}

app/templates/needdetail.html
{% extends 'base.html' %}
{% block title %}Search for - {{ search_parameter }}{% endblock %}

{% block page_content %}
<div id="demo">
  <h1>Details of the Knowlegde Carriers Domains {{ search_parameter }}</h1>

  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
    <div class=" btn card-panel hoverable">Details of the calculation</div>
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th colspan="2">Contribution</th>
          <th colspan="2">Relationship</th>
          <th colspan="4">Metadata</th>
            <th colspan="2">Profile</th>
        </tr>
      <tr>
      <th>Semantic</th>
      <th>Sentiment</th>
      <th>Type</th>
      <th>Strength</th>
      <th>Structural (Depth)</th>
          <th>Structural (Coverage)</th>
      <th>Descriptive</th>
      <th>Administrative</th>
      <th>Background</th>
      <th>Reputation</th>
      </thead>
      <tbody>
        {% for i in list %}
        <tr>
            <td data-title="ID">{{keywords[loop.index-1]}}</td>
         <td data-title="ID">{{list[loop.index-1][1]}}</td>
            <td data-title="ID">{{list[loop.index-1][2]}}</td>
            <td data-title="ID">{{list[loop.index-1][3]}}</td>
            <td data-title="ID">{{list[loop.index-1][4]}}</td>
            <td data-title="ID">{{list[loop.index-1][5]}}</td>
            <td data-title="ID">{{list[loop.index-1][6]}}</td>
            <td data-title="ID">{{list[loop.index-1][7]}}</td>
            <td data-title="ID">{{list[loop.index-1][8]}}</td>
            <td data-title="ID">{{list[loop.index-1][9]}}</td>

        </tr>
      {% endfor %}
      </tbody>
    </table>



</div>
{% endblock %}

app/templates/orientdb.html
{% extends "material/base.html" %}
{% block title %}SOM to FCM{% endblock %}
{% block head %}
{{ super() }}
    <style>
        body {
            padding-top: 30px;
			margin:25px;
            padding-bottom: 20px;

        }
        #viz {

        }

        text {
            pointer-events: none;
            fill: #fff;
        }

        .grandparent text {
            font-weight: normal;
            fill: #000;
        }

        rect {
            fill: none;
            stroke: #fff;
        }

        rect.parent, .grandparent rect {
            stroke-width: 2px;
        }

        .grandparent rect {
            fill: #fff;
        }

        .grandparent:hover rect {
        }

        .children rect.parent, .grandparent rect {
            cursor: pointer;
        }

        rect.parent {
            pointer-events: all;
        }
    </style>
{% endblock %}
{% block content %}

<h1>OrientDB of FCM's of CS - Stackoverflow - Dataset</h1>
  <br><br>
  <p>Use Username: admin and password: admin to explore the FCM Database<p>
  <a href='http://knowtology.com:2484/studio/index.html'>Go to OrientDB </a>
  <!-- <div>&copy; Wehrlem</div> -->
{% endblock %}

app/templates/post.html
{% extends 'base.html' %}
{% block title %}Post - {{ post.ID }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <div class="profile-header">
        <h1>{{  post.Title }}</h1>
        <p>Last edited {{ post.LastActivityDate }}. Created {{ post.CreationDate }}.</p>
        <div class="card-panel hoverable" style="border: 1px #9C27B0 solid">{{ post.Body }}</div>

    </div>
</div>
    {% if answers[0] is defined %}
    {% for i in answers %}
        <div class="card-panel">{{ i.Body }}</div>
    {% endfor %}
    {% endif %}
{% endblock %}

app/templates/posts.html
{% extends 'base.html' %}
{% block title %}Contributions{% endblock %}

{% block page_content %}
<div id="demo">
  <h1>Contributions</h1>

    <div class="sw">
    <form action="{{ url_for('posts.get_posts',q=q) }}" method="get">
      <input type="search" name="q" class="search" placeholder="Search for a post" />
      <button class="go"><span class="entypo-search"></span></button>
    </form>
  </div>


  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th>Author</th>
          <th>Content</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
      {% for i in list %}
        <tr>
          <td data-title="Name"><a href="{% if i.username[0] %}{{ url_for('experts.user', username=i.username[0]) }}{% endif %}">{{i.username[0]}}</a></td>
          <td data-title="Link">
            <a href="{{ url_for('posts.get_post', postid=i.PostId) }}">{{  i.Body|wordwrap }}</a>
          </td>
          <td data-title="Status">{{ i.PostType }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% if list[0] is not defined %}
      <h4>No results found</h4>
  {% endif %}
  </div>
</div>
{% if pagination %}
    {{ pagination.links }}
{% else %}
    <a href="{{ url_for('experts.get_experts') }}">Back to the overview</a>
{% endif %}
{% endblock %}

app/templates/result.html
{% extends 'base.html' %}
{% block title %}Search for - {{ search_parameter }}{% endblock %}

{% block page_content %}
<div id="demo">
  <h1>Search for - {{ search_parameter }}</h1>

  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
    <div class=" btn card-panel hoverable">Concepts</div>
        <div class="card-panel">{{ keywords }}</div><br>
    <div class=" btn card-panel hoverable">Query Results</div>

    <div class="card-panel table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th>Author</th>
          <th>Contribution</th>
            <th>Score</th>
        </tr>
      </thead>
      <tbody>
      {% for i in list['hits']['hits'] %}
        <tr>
          <td data-title="Link">
            {{ i['_source']['author'] }}
          </td>
          <td data-title="Answer">  <a href="{{ url_for('posts.get_post', postid=i['_id']) }}">{% if i['_source']['title'] %}{{ i['_source']['title'] }}{% else %}{{ i['_source']['text'] }}{% endif %}</a>
</td><td data-title="Score">{{ i['_score'] }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% if list['hits']['total'] ==0 %}
      <h4>No results found</h4>
  {% endif %}
  </div><br>
            <a href="{{ url_for('surface.index',q=search_parameter,e='TRUE') }}" class="btn button">Check for Knowledge Carriers</a>

        </form>
<br>


</div>
{% endblock %}